# Base bashrc configuration - generated by setup script

# Enable color support
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
fi


alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gcm='git commit -m'
alias gp='git push'
alias gpl='git pull'
alias gd='git diff'
alias gco='git checkout'
alias gb='git branch'
alias gl='git log --oneline'
alias gla='git log --oneline --all --graph'

# Modern CLI tool aliases and setup
if command -v eza >/dev/null 2>&1; then
    alias ls='eza --color=always --group-directories-first'
    alias ll='eza -la --color=always --group-directories-first'
    alias la='eza -a --color=always --group-directories-first'
    alias lt='eza -T --color=always --group-directories-first'
fi

if code-insiders --version >/dev/null 2>&1; then
    alias ci='code-insiders'
fi

if command -v bat >/dev/null 2>&1; then
    alias cat='bat --paging=never'
    alias bathelp='bat --plain --language=help'
    export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi

# FZF configuration - compact mode
if command -v fzf >/dev/null 2>&1; then
    export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
    export FZF_CTRL_T_OPTS="--preview 'bat --color=always --style=numbers --line-range=:500 {}'"
    export FZF_ALT_C_OPTS="--preview 'eza --tree --color=always {} | head -200'"
    
    # Use ripgrep for fzf if available
    if command -v rg >/dev/null 2>&1; then
        export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
        export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    fi
fi

# Zoxide setup
if command -v zoxide >/dev/null 2>&1; then
    eval "$(zoxide init bash)"
    alias cd='z'
fi

# Bash-preexec setup for atuin integration (bash only)
if [[ "bash" == "bash" && -f "$HOME/.bash-preexec.sh" ]]; then
    source "$HOME/.bash-preexec.sh"
fi

# Atuin setup for command history
if command -v atuin >/dev/null 2>&1; then
    eval "$(atuin init bash)"
fi

# Delta git integration
if command -v delta >/dev/null 2>&1; then
    export GIT_PAGER=delta
fi

# AI coding assistants
alias cc='claude'
alias oc='opencode'

# Carapace completion setup with interactive menu
if command -v carapace >/dev/null 2>&1; then
    export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense'
    source <(carapace _carapace)
fi

# Starship prompt setup
if command -v starship >/dev/null 2>&1; then
    eval "$(starship init bash)"
fi

# Add Nix to PATH if it exists
if [[ -d "/nix/var/nix/profiles/default/bin" ]]; then
    export PATH="/nix/var/nix/profiles/default/bin:$PATH"
fi

# Enable bash completion menu selection
bind 'set show-all-if-ambiguous on'
bind 'set menu-complete-display-prefix on'
bind 'TAB:menu-complete'
bind '"\e[Z":menu-complete-backward'

# Bash completion setup
if [[ -f "/nix/var/nix/profiles/default/share/bash-completion/bash_completion" ]]; then
    source "/nix/var/nix/profiles/default/share/bash-completion/bash_completion"
fi

# Source custom bashrc if it exists
if [[ -f "$HOME/.bashrc.custom" ]]; then
    source "$HOME/.bashrc.custom"
fi

# Add local bin to PATH if it exists
if [[ -d "$HOME/.local/bin" ]]; then
    export PATH="$PATH:$HOME/.local/bin"
fi

# Source Rust cargo environment if it exists
if [[ -f "$HOME/.cargo/env" ]]; then
    . "$HOME/.cargo/env"
fi
