# Base Nushell configuration - generated by setup script

# Configure completions
$env.config = {
    show_banner: false
    completions: {
        case_sensitive: false
        quick: true
        partial: true
        algorithm: "fuzzy"
    }
    history: {
        max_size: 10000
        sync_on_enter: true
        file_format: "plaintext"
    }
    cursor_shape: {
        emacs: line
        vi_insert: block
        vi_normal: underscore
    }
}

# Add Nix to PATH if it exists
if ("/nix/var/nix/profiles/default/bin" | path exists) {
    $env.PATH = ($env.PATH | prepend "/nix/var/nix/profiles/default/bin")
}

# Modern CLI tool aliases
if (which eza | is-not-empty) {
    alias ls = eza --color=always --group-directories-first
    alias ll = eza -la --color=always --group-directories-first
    alias la = eza -a --color=always --group-directories-first
    alias lt = eza -T --color=always --group-directories-first
}

if (which bat | is-not-empty) {
    alias cat = bat --paging=never
}

# AI coding assistants
alias cc = claude
alias oc = opencode

# Zoxide setup
if (which zoxide | is-not-empty) {
    zoxide init nushell | save -f ~/.config/nushell/zoxide.nu
    source ~/.config/nushell/zoxide.nu
    alias cd = z
}

# Atuin setup
if (which atuin | is-not-empty) {
    atuin init nu | save -f ~/.config/nushell/atuin.nu
    source ~/.config/nushell/atuin.nu
}

# Carapace completion setup
if (which carapace | is-not-empty) {
    mkdir ~/.cache/carapace
    carapace _carapace nushell | save -f ~/.cache/carapace/init.nu
    source ~/.cache/carapace/init.nu
}

# Source custom config if it exists
if ("~/.config/nushell/config.custom.nu" | path expand | path exists) {
    source ~/.config/nushell/config.custom.nu
}


source $"($nu.home-path)/.cargo/env.nu"
